export interface NigerianPlant {
  id: string
  imageName: string
  plantName: string
  scientificName: string
  localNames: string
  partsUsed: string
  uses: string
  benefits: string
  sideEffects: string
  locationFound: string
  dateCollected: string
  deviceUsed: string
  category: string
  difficulty: "Easy" | "Medium" | "Hard"
  popularity: number
  imageUrl: string
}

export const nigerianPlantsData: NigerianPlant[] = [
  {
    id: "1",
    imageName: "Azadirachta Indica (Neem)",
    plantName: "Neem",
    scientificName: "Azadirachta indica",
    localNames: "Dongoyaro (Hausa), Dongoyaro (Yoruba), Atu Yabasi (Igbo)",
    partsUsed: "leaves, bark, seeds, and even the oil extracted from them",
    uses: "Leaves: Neem leaves are widely used for their antiseptic, antibacterial, and antifungal properties. They can be used to treat skin infections, wounds, and even dandruff. Bark: The bark of the neem tree is also used for its medicinal properties, particularly for treating inflammation and infections. Seeds: Neem seeds contain a potent oil (Oil of Margosa) that has various medicinal uses, including as a natural insecticide and for wound healing. Oil: Neem oil is widely used for its antiseptic, antifungal, and antibacterial properties, and it is used for its potential wound-healing properties.",
    benefits:
      "Benefits of neem include: Diabetes management, boosts immunity, supports digestive health, speeds up wound healing, supports oral health, acne treatment, clears dandruff and head lice, and can improve skin health.",
    sideEffects: "Long-term consumption of neem extracts may cause severe skin dryness.",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 95,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Neem+Tree",
  },
  {
    id: "2",
    imageName: "Benin ju-ju tree",
    plantName: "Boundary tree",
    scientificName: "Newbouldia laevis",
    localNames: "ewe Akoko (Yoruba), Ogilisi (Igbo), Aduruuku (Hausa)",
    partsUsed: "root, bark, leaves, and stem",
    uses: "Leaves: Used for treating fever, pain, inflammation, epilepsy, and convulsions. Leaf extracts have been shown to have analgesic, anti-inflammatory, and anticonvulsant properties. Used to treat gastrointestinal disorders, such as dysentery, diarrhea, and stomach ache. Used to treat malaria. Used to treat sickle cell anemia and other blood-related issues. Root: Used for treating fever, rheumatism, and arthritis. Root decoctions can be used to treat toothache and stomachache. Used to treat epilepsy and convulsions in children. Bark: Used for treating epilepsy and convulsions in children. Used for treating rheumatism and painful arthritis of the knees. Stem: Used for treating epilepsy and convulsions in children. Stem bark decoctions can be used to treat pain and inflammation.",
    benefits:
      "Laevis is widely used in folk medicine to treat malaria, cough, stomach aches and pains, toothache, breast cancer, and constipation. In southeast and Midwest Nigeria, the plant is well known for treating inflammation, oedema, septic wounds, eye problems, and sexually transmitted infections (STIs).",
    sideEffects:
      "These side effects can include kidney, heart, and liver damage, as well as potential electrolyte imbalances and dyslipidemia.",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 75,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Boundary+Tree",
  },
  {
    id: "3",
    imageName: "Bitter kola leaf",
    plantName: "Bitter Kola",
    scientificName: "Garcinia kola Heckel",
    localNames: "Orogbo (Yoruba) Akilu or Aku-ilu (Igbo) and Namijin goro (Hausa)",
    partsUsed: "The seeds, also known as kola nuts",
    uses: "Seeds: The seeds are the most prized part of the bitter kola plant, and are often chewed or used in herbal preparations. They are believed to have numerous medicinal benefits, including treating digestive issues, coughs, bronchitis, fever, and arthritis.",
    benefits: "Treating digestive issues, coughs, and bacterial infections",
    sideEffects:
      "These include insomnia, digestive discomfort, nervousness, heart palpitations, and even possible allergic reactions.",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 88,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Bitter+Kola",
  },
  {
    id: "4",
    imageName: "Bitter leaf",
    plantName: "Bitter leaf",
    scientificName: "Vernonia amygdalina",
    localNames: "Ewuro (Yoruba), Shiwaka (Hausa) and Onugbu (Igbo)",
    partsUsed: "Leaves, stems, and roots",
    uses: "Leaves: The leaves are the most commonly used part of the plant. They are used for various ailments, including malaria, fevers, and as a digestive aid. The young leaves are also used in traditional medicine as anthelmintic, laxative, and expectorant. The stems and root are used medicinally too.",
    benefits:
      "Detoxification, immune support, and potential anti-cancer properties. It's also known to regulate blood sugar and blood pressure, and some studies suggest it may help with male and female reproductive health.",
    sideEffects: "Allergic reactions, digestive issues like vomiting and diarrhea, and damage to vital organs",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Easy",
    popularity: 92,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Bitter+Leaf",
  },
  {
    id: "5",
    imageName: "bush fig",
    plantName: "African Fig Tree or Broom Cluster Fig",
    scientificName: "Ficus sur",
    localNames: "Opoto (Yoruba), Akankoro (Igbo) and Dullu (Hausa)",
    partsUsed: "fruit, leaves, bark, latex, and roots",
    uses: "Fruit: Used as a laxative for constipation, and in some traditions, as a remedy for diabetes and other ailments. Leaves: Used for a wide range of conditions, including stomach disorders, hemostatic ophthalmia, coughs, hemorrhoids, anxiety, epilepsy, high blood pressure, rheumatism, arthritis, cancer, intestinal pains, and wounds. Bark: Employed as a mouthwash for spongy gum conditions, dysentery, menorrhea, hemoptysis, and diabetes. Latex: Used in traditional medicine to treat boils, diarrhea, dysentery, hemorrhoids, and even stomachaches. Root: The sap is given for gonorrhea, diabetes, and as a topical application for mumps and other inflammatory glandular enlargements.",
    benefits:
      "promoting digestive health with high fiber content, potentially aiding in weight management, and providing essential vitamins and minerals like calcium and potassium",
    sideEffects:
      "Fresh or dried fig fruit is LIKELY SAFE for most people when used in food amounts. Fig LEAF is POSSIBLY SAFE for most people when taken by mouth for up to one month as a medicine. However, in high doses, fig LATEX, the sap from the tree, might cause bleeding in the digestive tract in some people.",
    locationFound: "Osungboye",
    dateCollected: "20th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 70,
    imageUrl: "/placeholder.svg?height=300&width=300&text=African+Fig",
  },
  {
    id: "6",
    imageName: "Citrus Limon (Lemon)",
    plantName: "Lemon tree",
    scientificName: "Citrus Limon",
    localNames: "Iyanla or Iyanla Awo (Yoruba)",
    partsUsed: "peel, juice, and leaves",
    uses: "Lemon Fruit and Juice: Vitamin C: Lemon juice is rich in vitamin C, which is an antioxidant that can help prevent scurvy and support the immune system. Antiseptic: Lemon juice has antibacterial properties and has been used traditionally to treat open wounds. Kidney Stones: Citric acid in lemon juice may help dissolve small kidney stones. Digestion: Lemon juice can aid digestion. Inflammation: Lemon may help reduce pain and swelling. Lemon Peel: Antioxidants: Lemon peel contains antioxidants that can protect against cell damage and may have anti-cancer properties. Anti-inflammatory: Lemon peel may have anti-inflammatory effects, potentially reducing the risk of certain diseases. Cholesterol: Studies have shown that lemon peel can help lower liver cholesterol levels. Antibacterial: Lemon peel extract has shown antibacterial activity against various pathogens. Body Scrub: Lemon peels can be used as a natural body scrub. Lemon Leaves: Calming Properties: Lemon leaves are rich in compounds that can have calming and antispasmodic effects, making them useful for insomnia, headaches, and asthma. Anti-inflammatory: Lemon leaves can be used as an anti-inflammatory when applied as an essential oil or used in tea. Diuretic: Lemon leaves can act as a natural diuretic when steeped in hot water. Memory and Cognitive Function: Extracts from lemon leaves have shown potential to improve memory and cognitive performance in studies.",
    benefits:
      "They can boost immunity, support heart health, and potentially aid in weight management. Lemons also contribute to kidney stone prevention, protection against anemia, and may reduce cancer risk.",
    sideEffects:
      "The most common reactions are itching, burning, or swelling of the mouth and throat. Some people can have headaches or gastrointestinal distress. Lemon juice is high in the amino acid tyramine. If you are sensitive to tyramine, drinking lemon juice can trigger migraine headaches.",
    locationFound: "Ago-iwoye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "iphone11",
    category: "fruit",
    difficulty: "Easy",
    popularity: 95,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Lemon+Tree",
  },
  {
    id: "7",
    imageName: "common wireweed",
    plantName: "Common wireweed",
    scientificName: "Sida acuta",
    localNames: "Isekotu (Yoruba), Udo or Ire-agwo (Igbo)",
    partsUsed: "leaves, roots, and whole plant",
    uses: "The leaves are used to treat abdominal pain, hemorrhoids, infertility, fever, headache, diarrhea, and dysentery, and are also applied for wound care and in vapor baths for venereal diseases and toothache. Additionally, they serve as a tea substitute, and the leaf juice is mixed with coconut oil for application on the head. The root juice is applied to wounds, while the roots are valued as a bitter tonic, emollient, aphrodisiac, antipyretic, vulnerary, and chewed to relieve toothache. Bark: Used for measles.",
    benefits: "Anti-inflammatory, Digestive health, Wound healing, Antidiarrheal, Respiratory health",
    sideEffects: "including high blood pressure, heart attacks, loss of consciousness, and death.",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 60,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Wireweed",
  },
  {
    id: "8",
    imageName: "Copper leaf",
    plantName: "copperleaf, Jacob's coat",
    scientificName: "Acalypha wilkesiana",
    localNames: "aworoso (Yoruba), Aba (Igbo) and Jiwene or Jinwinini (Hausa)",
    partsUsed: "The leaves, roots, and sap",
    uses: "The leaves, commonly consumed as a vegetable, are used to manage hypertension, diabetes, gastrointestinal issues, fungal infections, and are also believed to have diuretic properties in Southern Nigeria. Root infusions or decoctions are traditionally used to treat asthma, cleanse the liver and kidneys, and relieve intestinal worms and stomach ache. The leaf sap serves as an emetic and is sometimes combined with other plants for enhanced medicinal effects.",
    benefits:
      "Skin Conditions: The expressed juice or boiled decoction of copperleaf has been used for treating various skin conditions, including fungal infections like Pityriasis versicolor, Impetigo contagiosa, Candida intertrigo, Tinea versicolor, Tinea corporis, and Tinea pedis. Gastrointestinal Issues: It has been traditionally used to treat gastrointestinal disorders, potentially due to its soothing and anti-inflammatory effects. Hypertension and Diabetes: In some regions, the leaves are consumed as vegetables to help manage hypertension. Studies have also shown that it may have some effect on blood sugar levels, potentially aiding in diabetes management. Respiratory Issues: Some traditional practices use copperleaf to relieve respiratory issues like coughs and colds.",
    sideEffects:
      "Copper leaf can cause several adverse effects mainly related to ingestion. Ingestion can lead to nausea, vomiting, diarrhea, and abdominal pain.",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "iphone11",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 78,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Copper+Leaf",
  },
  {
    id: "9",
    imageName: "Currant tomato",
    plantName: "Currant tomato",
    scientificName: "Solanum pimpinellifolium",
    localNames: "tomato ogbe (Yoruba), adaba (Hausa), and tomato ogbo (Igbo)",
    partsUsed: "The fruit can be used for skin issues like oily skin, burns, and sunburns",
    uses: "Currant tomatoes, with their small size and vibrant color, are versatile and have a wide range of uses in both culinary and medicinal contexts.",
    benefits:
      "Currant tomatoes offer various health benefits due to their high concentration of antioxidants and vitamins, particularly lycopene.",
    sideEffects: "These can include allergic reactions, gastrointestinal issues, and acid reflux.",
    locationFound: "Various",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "iphone11",
    category: "fruit",
    difficulty: "Easy",
    popularity: 65,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Currant+Tomato",
  },
  {
    id: "10",
    imageName: "Efo iyanapaja",
    plantName: "Chaya or Hospital Too Far",
    scientificName: "Cnidoscolus aconitifolius",
    localNames: "Ugu Oyibo (Igbo), Hospital Too Far (Pidgin English), Iyana Ipaja or Lapalapa (Yoruba)",
    partsUsed: "The leaves and shoots are commonly used as a laxative, diuretic, and lactation stimulant",
    uses: "It's believed to be beneficial for conditions like alcoholism, insomnia, gout, and scorpion stings.",
    benefits: "it can improve blood circulation, aid digestion, boost memory, and even help with weight loss.",
    sideEffects: "vomiting, diarrhea, abdominal pain, and a burning sensation in the throat.",
    locationFound: "Onihale, Osungboye",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 72,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Chaya+Plant",
  },
  {
    id: "11",
    imageName: "Efo tete",
    plantName: "African spinach or callaloo",
    scientificName: "Amaranthus hybridus",
    localNames: "Efo tete (Yoruba) and Inine (Igbo)",
    partsUsed: "The leaves, root, and sap are traditionally used in various ways for health benefits",
    uses: "It's primarily used as an ingredient in soups, stews, and salads, and can also be blended into juices.",
    benefits:
      "Efo tete (African spinach) offers numerous health benefits, including improved digestion, constipation relief, and a rich source of vitamins and minerals.",
    sideEffects:
      "lead to digestive issues like bloating and gas, especially for those not accustomed to a high-fiber diet.",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "vegetable",
    difficulty: "Easy",
    popularity: 85,
    imageUrl: "/placeholder.svg?height=300&width=300&text=African+Spinach",
  },
  {
    id: "12",
    imageName: "Ewe Akintola",
    plantName: "Akintola leaf",
    scientificName: "Chromolaena odorata",
    localNames: "Ewe Akintola (Yoruba), Obiarakara, Ugbogashi, or Awolowo (Igbo), Obiarakara (Hausa)",
    partsUsed: "The leaves, stems, and roots are often utilized",
    uses: "Treatment of various ailments, Antimicrobial properties, Anthelmintic properties, diarrhea, malaria fever, toothache and skin diseases.",
    benefits: "Cyst Medicine, Pain reliever, Prevent cervical cancer, Prevent diabetes, Ulcer medicine.",
    sideEffects: "Gastrointestinal upset, allergic reactions, lowered blood sugar levels",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 68,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Akintola+Leaf",
  },
  {
    id: "13",
    imageName: "Ewe Eje",
    plantName: "Bellyache bush, Cotton-leaf physic nut",
    scientificName: "Jatropha gossypiifolia",
    localNames: "Ewe Eje (Yoruba), Ncheogwu (Igbo), Bini da zugu or Lapalapa ja (Hausa)",
    partsUsed: "Leaves",
    uses: "Leaves: Used for anti-inflammatory, antimicrobial, and insecticidal applications.",
    benefits:
      "it is antimicrobial, antipyretic, antianemic, anti-inflammatory, antibacterial, antioxidant, analgesic, antidiabetic, antidiarrheal",
    sideEffects:
      "Bellyache bush (also known as Jatropha gossypiifolia) is a plant that is poisonous to humans and animals when ingested.",
    locationFound: "Onihale",
    dateCollected: "20th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 55,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Bellyache+Bush",
  },
  {
    id: "14",
    imageName: "ewe lapalapa",
    plantName: "red physic nut",
    scientificName: "Jatropha gossypifolia",
    localNames: "Ewe Lapalapa or Ewe Iyalode (Yoruba), Bini da Zugu (Hausa), Olulu idu or Owulu idu (Igbo)",
    partsUsed: "leaves, sap, roots, and branches",
    uses: "Leaves: wound healing, skin infections, anti-inflammatory and fertility & menstruation. Stem & Bark: Toothache relief and Snake bite treatment. Roots: Malaria & fever and Internal cleansing. Sap (latex): Purgative and anti-parasitic.",
    benefits: "Blood purification and detox, menstrual and fertility support, traditional snakebite remedy.",
    sideEffects: "Toxicity, internal bleeding risk, pregnancy risk and oral irritation",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "iphone11",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 60,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Red+Physic+Nut",
  },
  {
    id: "15",
    imageName: "Ewe lapalapa funfun",
    plantName: "physic nut",
    scientificName: "Jatropha Curcas",
    localNames: "Bini da Zugu (Hausa), odo-ala (Igbo), Botuje (Yoruba)",
    partsUsed: "Latex, Leaves",
    uses: "Treatment of wounds and injuries, cough and respiratory issues, anti-inflammatory, digestive issues, pain relief.",
    benefits:
      "speeds up wound healing, relieves cough and chest congestion, aids digestion and stops diarrhea, acts as a natural pain reliever",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 70,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Physic+Nut",
  },
  {
    id: "16",
    imageName: "Flaming katy",
    plantName: "Flaming Katy",
    scientificName: "Kalanchoe blossfeldiana",
    localNames: "Igbo Igboro (Igbo), Yoruba Iruku (Yoruba)",
    partsUsed: "Leaves, Juice, plant paste, leaf paste, sap",
    uses: "Leaves: The leaves are a primary source of medicinal compounds and are used for a wide range of ailments, including inflammation, infections, and even cancer. Juice: The juice of the leaves is used to treat kidney stones, with some scientific evidence supporting this practice. Plant paste: Plant paste can be applied to the forehead for headache relief. Leaf paste: Leaf paste is used externally to heal cuts and wounds. Sap: The fresh sap is used for eye diseases.",
    benefits: "anti-inflammatory, antimicrobial, wound-healing, muscle relaxing, and antitumor activities",
    sideEffects: "vomiting, diarrhea, and lethargy",
    locationFound: "Ago-iwoye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "iphone11",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 75,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Flaming+Katy",
  },
  {
    id: "17",
    imageName: "Gale of the wind",
    plantName: "Gale of the wind or stonebreaker",
    scientificName: "Phyllanthus niruri",
    localNames: "Eyin Olobe (Yoruba), Enyikwonwa (Igbo), Geeron tsuntstsaaye (Hausa)",
    partsUsed: "Leaves, Stem, Roots",
    uses: "Leaves: treats liver problems (especially hepatitis and jaundice). Stem: Used for treating kidney stones, gallstones, and detoxifying the liver. Roots: Used to treat fever, skin infections, and digestive issues.",
    benefits:
      "treats kidney stones, supports liver health, fights viral infections, controls blood sugar, reduces blood pressure, boosts immune system.",
    sideEffects: "Hypoglycemia, Hypotension, Stomach upset",
    locationFound: "Onihale",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 82,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Stonebreaker",
  },
  {
    id: "18",
    imageName: "Heliotropium indicum",
    plantName: "Heliotropium indicum",
    scientificName: "Heliotropium indicum",
    localNames: "Ogbe ori Akuko (Yoruba)",
    partsUsed: "Leaves",
    uses: "the leaves are the most commonly utilized part of the plant. These leaves are used for various ailments, including fever, insect bites, stings, diarrhea, skin rashes, menstrual disorders, and urticaria.",
    benefits:
      "Heliotropium indicum is traditionally used for various ailments, including treating skin conditions, fevers, and inflammation.",
    sideEffects: "liver damage and even death in some cases.",
    locationFound: "Osungboye",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 45,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Heliotropium",
  },
  {
    id: "19",
    imageName: "Henna leaf",
    plantName: "Henna leaf plant",
    scientificName: "Lawsonia inermis",
    localNames: "Lalle (Hausa), Laali (Yoruba)",
    partsUsed: "Leaves",
    uses: "the leaves are used to treat various ailments, including poliomyelitis, measles, amoebic dysentery, sore throats, and skin conditions like wounds and ulcers. The leaves are also employed as an expectorant and hematinic for febrile disorders, hemicranias, cephalalgia, leukoderma, and ophthalmia. Additionally, the leaves are used to prepare decoctions and ointments for wound healing and burns.",
    benefits: "Henna contains substances that might help fight certain infections.",
    sideEffects:
      "It can cause some side effects such as inflammation of the skin (dermatitis) including redness, itching, burning, swelling, scaling, broken skin, blisters, and scarring of the skin.",
    locationFound: "Onihale",
    dateCollected: "19th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 70,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Henna+Plant",
  },
  {
    id: "20",
    imageName: "Jute leaf",
    plantName: "Jute leaf",
    scientificName: "Corchorus olitorius",
    localNames: "Ewedu (Yoruba), Ahinghara (Igbo), Rama (Hausa)",
    partsUsed: "Leaves",
    uses: "As a vegetable, jute leaf is full of antioxidants that have been linked to protection against several medical illnesses as well as chronic diseases like cancer, diabetes, heart disease, and hypertension. Herbal tea is basically made from a combination of different plants' leaves, seeds, and/or roots",
    benefits:
      "boosting immunity, improving digestion, supporting skin and hair health, reducing cholesterol, and potentially preventing certain types of cancer.",
    sideEffects: "skin rashes, itching, and gastrointestinal discomfort",
    locationFound: "Onihale, Osungboye",
    dateCollected: "19th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "vegetable",
    difficulty: "Easy",
    popularity: 88,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Jute+Leaf",
  },
  {
    id: "21",
    imageName: "Lara pupa",
    plantName: "red-stemmed castor plant",
    scientificName: "Ricinus communis",
    localNames: "Lara pupa (Yoruba)",
    partsUsed: "Leaves and seeds",
    uses: "Leaves: used in application to treat cuts and wounds. Seeds: Used to make ogiri, a traditional Igbo dish.",
    benefits:
      "Lara pupa is used for anti-inflammatory, anti-hemorrhagic, analgesic, and antimicrobial properties, and is also used to promote good luck and spiritual protection.",
    sideEffects:
      "Common side effects include dizziness, back pain, upper respiratory tract infections, nasal congestion, and cough",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 58,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Castor+Plant",
  },
  {
    id: "22",
    imageName: "Lemongrass",
    plantName: "lemongrass",
    scientificName: "Cymbopogon citratus",
    localNames: "Tsauri (Hausa), Myoyaka makara (Ibibio), Achara (Igbo), Kooko oba (Yoruba), Ewe tea (Yoruba)",
    partsUsed: "Leaves and oil",
    uses: "In Nigeria, the leaves have been traditionally used to treat a variety of ailments, including digestive issues, stomachaches, coughs, and fever. Oil: Lemongrass oil can be applied directly to the skin for various purposes, such as relieving pain, reducing inflammation, or treating skin conditions. The oil can be inhaled for aromatherapy, which can help relieve stress, improve mood, and promote relaxation.",
    benefits: "Treating digestive issues, colds, fever, and pain",
    sideEffects: "Potential side effects include dizziness, drowsiness, dry mouth, and increased urination.",
    locationFound: "Onihale",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "herb",
    difficulty: "Easy",
    popularity: 90,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Lemongrass",
  },
  {
    id: "23",
    imageName: "Mangifera Indica (Mango)",
    plantName: "Mango",
    scientificName: "Mangifera Indica",
    localNames: "Mangoro (Yoruba), Mangolo (Igbo), Mangwaro (Hausa)",
    partsUsed: "leaves, bark, fruit, seed kernels, and roots",
    uses: "Leaves: Used as a tea or extract to reduce fever, treat coughs, diarrhea, and even intestinal worm infestations. Bark: Used as a lotion or infusion for toothaches, sore gums, and sore throats. It can also be used to treat malaria, diarrhea, and dysentery. Fruit: The seed kernel can be used to treat Type 2 Diabetes and obesity, according to researchers. Seed Kernels: Mashed kernels can be used to make bread or butter and are also used in extracts or powder form to treat Type 2 Diabetes and obesity. Roots: The roots are also used in traditional medicine, though their specific uses are not as widely documented as the leaves and bark.",
    benefits:
      "Anti-oxidant and anti-inflammatory, digestive health, weight management and diabetes, wound healing, gastrointestinal issues",
    sideEffects: "Digestive issues, weight gain, electrolyte imbalance, allergic reactions, skin reaction",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "fruit",
    difficulty: "Easy",
    popularity: 95,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Mango+Tree",
  },
  {
    id: "24",
    imageName: "Mentha (Mint)",
    plantName: "Mint leaf",
    scientificName: "Mentha",
    localNames: "Ewe minti (Yoruba), na'a naa (Hausa), efinrin nla or efirin (Yoruba)",
    partsUsed: "the leaves, flowers, stems, and essential oils",
    uses: "Leaves: The most commonly used part of the mint plant, used in teas, beverages, and for their refreshing aroma. They are also used to make essential oils, which have anti-microbial and anti-inflammatory properties. Flowers: While less common, mint flowers are also used in teas and beverages, contributing to the overall flavor profile. Stems: Mint stems, often overlooked, can be used in similar ways to the leaves, adding flavor to dishes and infusions. Essential Oils: These oils, derived from both the leaves and stems, are used in aromatherapy for their calming and invigorating properties. They can be inhaled or used topically for various conditions.",
    benefits:
      "soothe digestive discomfort, including nausea and indigestion, help regulate stomach muscles, contributing to better digestion, help alleviate congestion and is often used for colds, Its soothing properties can treat sore throats and respiratory irritation and Mint's antibacterial properties can help treat acne and soothe skin.",
    sideEffects:
      "Mint can relax the lower esophageal sphincter, potentially triggering acid reflux and heartburn. This is why it's often recommended to avoid mint if you have GERD and some individuals may be allergic to mint, experiencing skin irritation, rashes, or breathing difficulties.",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "herb",
    difficulty: "Easy",
    popularity: 92,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Mint+Plant",
  },
  {
    id: "25",
    imageName: "Miracle leaf",
    plantName: "Miracle leaf",
    scientificName: "Bryophyllum pinnatum",
    localNames: "Ewe Abamoda (Yoruba)",
    partsUsed: "The leaves are commonly used, with their juice or extracts and roots",
    uses: "Used for ailments like fevers, stomachaches, kidney stones, and wounds. The root is used for high blood pressure, liver health, and tuberculosis.",
    benefits:
      "The leaf is used to make herbal teas and tonics to relieve coughs and respiratory issues. The leaf is used to alleviate pain and headaches. The leaf is applied to wounds, boils, and insect bites for healing and to treat ulcers. The juice of the leaves is used to prevent and treat kidney stones. The leaf is used to help manage blood sugar levels. The leaf is used for its wound healing properties, including the detachment of the umbilicus of infants. The juice of the leaves is used as a general tonic to boost overall health. The leaf is used to relieve ear pain.",
    sideEffects:
      "large quantities or prolonged use can lead to gastrointestinal distress like nausea, vomiting, and diarrhea",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Easy",
    popularity: 85,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Miracle+Leaf",
  },
  {
    id: "26",
    imageName: "Moringa",
    plantName: "Moringa leaf",
    scientificName: "Moringa oleifera",
    localNames: "Adagba malero (Yoruba), Zogale ganji (Hausa), Odudu oyibo (Igbo)",
    partsUsed: "Leaves, Bark and Stems",
    uses: "Leaves: The most widely used part, used for treating a variety of ailments, including malaria, typhoid, and ear infections. They are also used to make poultices for inflammatory conditions and are a source of nutrients. Bark: Used to treat wounds and skin infections. Stems: Used to treat typhoid and malaria.",
    benefits:
      "Nutrient-rich, Liver protection, Brain health, Blood pressure regulation, Antimicrobial, and Antioxidant properties",
    sideEffects: "These include diarrhea, hypotension, mouth and throat sores, and possible liver or kidney damage",
    locationFound: "Ago-iwoye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "iphone11",
    category: "medicinal",
    difficulty: "Easy",
    popularity: 98,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Moringa+Tree",
  },
  {
    id: "27",
    imageName: "Murraya Koenigii (Curry)",
    plantName: "Curry leaf",
    scientificName: "Murraya koenigii",
    localNames: "efirin oso (Yoruba), marugbo sanyan (Hausa)",
    partsUsed: "Leaves",
    uses: "Aiding digestion, diabetes control, boosting immunity, skin conditions and reducing fever.",
    benefits:
      "Curry leaves are loaded with antioxidants, which help neutralize harmful free radicals in the body. The antioxidants in curry leaves, like vitamin C, vitamin A, and flavonoids, help fight oxidative stress, slow down aging, protect cells from damage, and lower the risk of chronic diseases.",
    sideEffects: "Allergic reactions, gastrointestinal discomfort, and potential impact on blood sugar levels",
    locationFound: "Osungboye",
    dateCollected: "12th Feb, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "herb",
    difficulty: "Easy",
    popularity: 80,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Curry+Leaf",
  },
  {
    id: "28",
    imageName: "Noni Cheese fruit",
    plantName: "Indian Mulberry",
    scientificName: "Morinda citrifolia",
    localNames:
      "Egan or Ega (fruit), Ogun (leaf) (Yoruba), Achi or Achi-nwa (fruit), Oka-achi (leaf) (Igbo), Hag Apple or Hog Apple (Hausa)",
    partsUsed: "Leaves, Roots, and Bark",
    uses: "Leaves: Noni leaves are used to prepare traditional remedies for rheumatic aches, joint pain, swelling, stomach problems, dysentery, and parasitic infections. Roots: The roots are utilized in traditional medicines to treat various ailments, including skin infections and stomach problems. Bark: Noni bark is used in the preparation of remedies for bacterial infections, coughs, diarrhea in infants, and stomach ailments.",
    benefits:
      "They are rich in vitamins and minerals, and have been traditionally used to treat various ailments, such as cuts, bruises, and rheumatic pain. Noni leaves offer benefits for digestive health, skin health, and even help in weight loss",
    sideEffects:
      "Liver Damage: Noni has been linked to several cases of liver damage. High Potassium Levels (Hyperkalemia): Noni contains high levels of potassium, which can be problematic for individuals with kidney disease or those already prone to high potassium levels. Drug Interactions: Noni may interact with certain medications, including those for high blood pressure, blood thinners, and diuretics. Digestive Issues: Some individuals may experience digestive issues like diarrhea, as noni can have a laxative effect.",
    locationFound: "Ago-iwoye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "iphone11",
    category: "fruit",
    difficulty: "Medium",
    popularity: 65,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Noni+Fruit",
  },
  {
    id: "29",
    imageName: "pawpaw",
    plantName: "Papaya",
    scientificName: "Carica papaya",
    localNames: "Gwanda (Hausa), Ogede Oyinbo or Okwuru bekee (Igbo), Ibepe (Yoruba)",
    partsUsed: "leaves, fruit, seeds, flowers, and roots",
    uses: "Leaves: Pawpaw leaves are widely used in traditional Nigerian medicine for various ailments, including malaria, typhoid fever, and dengue fever. They are also used as a heart tonic, vermifuge, and to treat colic and beriberi. Fruit: Both green and ripe pawpaw fruits have medicinal properties. Green fruits are used to treat conditions like malaria, hypertension, and diabetes. Ripe fruits are known for their digestive benefits. Seeds: Pawpaw seeds are sometimes used as a substitute for black pepper due to their sharp, spicy taste. Flowers: Pawpaw flowers are traditionally used to treat coughs, hoarseness, bronchitis, and other respiratory ailments. Roots: The roots of the pawpaw plant have been reported to contain antibacterial properties.",
    benefits:
      "Malaria: Pawpaw leaves are a traditional remedy for malaria in Nigeria, with decoctions of the leaves being taken to treat the disease. The antimalarial activity is linked to the ability of pawpaw to increase the antioxidant status of patients, which may help prevent anemia. Dengue Fever: Papaya leaf extract and juice are used to treat dengue fever symptoms. Anti-inflammatory: Pawpaw leaves have anti-inflammatory properties and have been found to reduce inflammation and swelling. Anti-microbial: Pawpaw leaves have antibacterial and antiviral properties. Skin and hair health: Pawpaw leaf extract is used to improve skin and hair health, potentially reducing dandruff and promoting hair growth. Digestive health: Pawpaw leaves can aid digestion and are believed to cleanse the digestive tract.",
    sideEffects: "Nausea and vomiting",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "fruit",
    difficulty: "Easy",
    popularity: 95,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Papaya+Tree",
  },
  {
    id: "30",
    imageName: "Psidium Guajava (Guava)",
    plantName: "Guava",
    scientificName: "Psidium Guajava",
    localNames: "goba (Hausa), guaba or gilofa (Yoruba), ugwoba (Igbo)",
    partsUsed: "Leaf and fruit",
    uses: "Various parts of the plant, including the leaf and the fruit, are used as medicine. People use guava leaf for stomach and intestinal conditions, pain, diabetes, and wound healing. The fruit is used for high blood pressure.",
    benefits: "Digestive health, diabetes management, infection control, reduce menstrual cramps",
    sideEffects:
      "Guava leaf extract cause temporary nausea, stomach pain, or skin irritation, particularly in individuals with sensitive skin or eczema. Overconsumption can lead to flatulence.",
    locationFound: "Osungboye",
    dateCollected: "19th April, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "fruit",
    difficulty: "Easy",
    popularity: 88,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Guava+Tree",
  },
  {
    id: "31",
    imageName: "Sandpaper plant",
    plantName: "Sandpaper tree or sandpaper fig",
    scientificName: "Ficus exasperata",
    localNames: "Ewe Ipin or Erepin (Yoruba), Anwerenwa or Asesa (Igbo), Baure (Hausa)",
    partsUsed: "leaves, bark, and sap",
    uses: "Leaves: Used for wound healing and skin infections, used in decoctions or macerations for treating stomach disorders, coughs, and hemorrhoids, used as an antipyretic in Nigeria. Bark: Used as a styptic or wound healer due to its astringent properties, decoctions are taken to treat worms, hemorrhoids, and abnormal spleen enlargement and can be used in preparations for heart problems. Sap: used for wound healing and to halt bleeding, some traditional healers consider it corrosive and dangerous to ingest and used to relieve itching.",
    benefits:
      "Sandpaper leaf (Ficus exasperata) is commonly used in folk medicine to manage high blood pressure. However, different methods such as soaking, boiling, hand maceration, and blending have been employed for preparing sandpaper leaf extracts for hypertensive patients.",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 75,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Sandpaper+Tree",
  },
  {
    id: "32",
    imageName: "Scent leaf",
    plantName: "Scent leaf",
    scientificName: "Ocimum gratissimum",
    localNames: "Efirin (Yoruba), nchanwu (Igbo), daidoya (Hausa)",
    partsUsed: "Leaves and stem",
    uses: "The leaves are used for treating skin infections, colds, and catarrh, while the stem can be used as a chewing stick to freshen breath and prevent tooth decay.",
    benefits: "Oral hygiene, skin conditions, malaria and fever, mosquito repellent, and pain relief.",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "herb",
    difficulty: "Easy",
    popularity: 90,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Scent+Leaf",
  },
  {
    id: "33",
    imageName: "Sodom apple leaf",
    plantName: "Sodom apple leaf",
    scientificName: "Calotropis procera",
    localNames: "Ewe bomubomu (Yoruba)",
    partsUsed: "Leaves",
    uses: "The leaves have been used to treat fevers, rheumatism, indigestion, colds, eczema, and diarrhea. The leaves are also used for stomatic, sinus fistula, and skin diseases, and are help with jaundice.",
    benefits: "Wound healing, treating infections, treating certain STIs, and diarrhea",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 65,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Sodom+Apple",
  },
  {
    id: "34",
    imageName: "Sugarcane leaf",
    plantName: "Sugarcane",
    scientificName: "Saccharum officinarum",
    localNames: "Ìrèke (Yoruba), Arakke (Hausa), Osisina-atuto or Okpete (Igbo)",
    partsUsed: "Leaves and stem",
    uses: "Fever and malaria, cough and sore throat, and wound healing.",
    benefits:
      "The stem pulp is consumed for its sugar content and is also believed to have some benefits against infectious diseases. Sugarcane leaf sap is used as eye drops and nose drops to treat eye problems, headache, and malaria in some regions.",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "plant",
    difficulty: "Easy",
    popularity: 70,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Sugarcane",
  },
  {
    id: "35",
    imageName: "Tobacco",
    plantName: "Tobacco leaf",
    scientificName: "Nicotiana tabacum",
    localNames: "Igbó or ewe taba (Yoruba), Utaba (Igbo), Taba (Hausa)",
    partsUsed: "Leaves",
    uses: "In Yoruba culture, Nicotiana tabacum is more than just a plant used for smoking. It has a long history of medicinal use, valued for its ability to treat various ailments. Yoruba herbalists have utilized its properties to create remedies for numerous conditions. Treatment of Infections: Yoruba traditional healers use Nicotiana tabacum to treat various infections. Its antimicrobial properties help fight bacteria and viruses, making it an effective natural remedy for infections. Wound Healing: Tobacco leaves are applied to wounds and cuts to promote healing. The plant's compounds help prevent infections and speed up the healing process. Alleviating Digestive Issues: Nicotiana tabacum is also used to alleviate digestive issues. It can help with conditions such as constipation and stomach pains when used appropriately.",
    benefits:
      "Pain Relief: Nicotiana tabacum is known for its analgesic properties. It is often used to relieve pain from headaches, muscle aches, and other conditions. Its pain-relieving effects are a key reason for its use in traditional medicine. Anti-inflammatory Properties: The anti-inflammatory properties of Nicotiana tabacum make it effective in reducing inflammation. It is used in remedies for conditions such as arthritis and skin inflammations. Respiratory Benefits: Tobacco has been traditionally used to treat respiratory issues. It is believed to help with conditions such as asthma and bronchitis, although modern usage cautions against its potential harmful effects.",
    sideEffects:
      "The most notable side effect is its addictive nature due to nicotine, which can lead to dependence and various health problems.",
    locationFound: "Ago-iwoye",
    dateCollected: "18th April,2025",
    deviceUsed: "iphone11",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 40,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Tobacco+Plant",
  },
  {
    id: "36",
    imageName: "Trigonella Foenum-graecum (Fenugreek)",
    plantName: "Fenugreek",
    scientificName: "Trigonella Foenum-graecum",
    localNames: "Eru (Yoruba), Kimba (Hausa), Mkpuru oka Oyinbo or Fenugreek (Igbo)",
    partsUsed: "The leaves and seeds",
    uses: "Fenugreek leaves may have antioxidant and anti-inflammatory properties. They have been traditionally used for skin conditions, like acne, and may help improve skin tone.",
    benefits:
      "Fenugreek is traditionally used to increase breast milk supply, the fiber content in fenugreek leaves can help soothe the digestive tract and promote bowel movements, Fenugreek seeds are considered an aid to digestion and can help with indigestion, bloating, and constipation.",
    sideEffects: "Allergic Reactions, and low blood sugar",
    locationFound: "Osungboye",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "herb",
    difficulty: "Medium",
    popularity: 75,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Fenugreek",
  },
  {
    id: "37",
    imageName: "Tropical almond",
    plantName: "Almond fruit or tropical almond",
    scientificName: "Terminalia catappa",
    localNames: "Igi furutu (Yoruba), Ebelebor (Delta)",
    partsUsed: "Leaves, bark and fruits",
    uses: "Wound healing, Antimicrobial, Antidiabetic, Antioxidant, Anticancer and improving immunity.",
    benefits:
      "Leaves and bark are used in herbal tea preparations for liver detoxification and immune support. Juice from leaves is used to make ointments for various skin conditions. The root bark is used to treat dysentery and diarrhea. Leaves can be used to treat mouth infections, fractures, and other conditions.",
    sideEffects:
      "Tropical almonds, also known as Indian almonds or Terminalia catappa, are generally safe for consumption in Nigeria, but there are potential side effects and considerations. Additionally, some individuals may experience diarrhea or other digestive issues after consumption.",
    locationFound: "Onihale",
    dateCollected: "18th April,2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "fruit",
    difficulty: "Easy",
    popularity: 70,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Tropical+Almond",
  },
  {
    id: "38",
    imageName: "Turnsole",
    plantName: "Turnsole plant",
    scientificName: "Heliotropium indicum",
    localNames: "Agogo Igun (Yoruba), Navel medicine (Ijo)",
    partsUsed: "Leaves, stem, root, and whole plant",
    uses: "Skin ailments, eye infections, ulcers, headaches, erysipelas, umbilical hernia, antipyretic and analgesic, antimicrobial",
    benefits: "Used for skin conditions and as a pain reliever",
    sideEffects:
      "Heliotropium indicum contains pyrrolizidine alkaloids, which can be toxic to the liver. Ingestion can lead to liver damage, potentially affecting the liver's ability to function properly.",
    locationFound: "Onihale",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Hard",
    popularity: 45,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Turnsole+Plant",
  },
  {
    id: "39",
    imageName: "Water leaf",
    plantName: "Water leaf plant",
    scientificName: "Talinum triangulare",
    localNames: "Gbure (Yoruba), Mgbolodi (Igbo), Ebe-dondon (Edo), Mmongmong ikong (Ibibio)",
    partsUsed: "The leaves are the primary part used for medicinal purposes",
    uses: "Anti-inflammatory, anti-fungal, anti-bacterial, diabetes Management, and cholesterol regulation.",
    benefits:
      "Schistosomiasis, Scabies, and Fresh Cuts: Leaf and root extracts are traditionally used to treat these conditions. Dropsy, Swellings, and Oedema: Some localities in Nigeria use waterleaf to treat these conditions. Cardiovascular Diseases: Waterleaf leaves are sometimes used to reduce cardiovascular risks. Antioxidant and Other Properties: Waterleaf is a good source of tannins, alkaloids, saponins, phenols, and flavonoids, which may contribute to its anti-inflammatory, anti-fungal, and anti-bacterial properties.",
    sideEffects: "Generally safe when used properly",
    locationFound: "Osungboye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "vegetable",
    difficulty: "Easy",
    popularity: 85,
    imageUrl: "/placeholder.svg?height=300&width=300&text=Water+Leaf",
  },
  {
    id: "40",
    imageName: "willow",
    plantName: "White willow plant",
    scientificName: "Deinbollia pinnata",
    localNames: "Ogiri-egba or Ekusi-Oloko (Yoruba), Akara (Igbo), Dogoyaro (Hausa)",
    partsUsed: "Inner bark",
    uses: "pain relief, reducing inflammation, and as a source of natural salicylic acid, similar to aspirin",
    benefits:
      "Willow trees, particularly the white willow bark, are traditionally used in Nigeria for their medicinal properties, including pain relief, anti-inflammatory effects, and potential heart health support.",
    sideEffects:
      "It might cause diarrhea, heartburn, and vomiting in some people. It can also cause itching, rash, and allergic reactions",
    locationFound: "Osungboye",
    dateCollected: "4th Jan, 2025",
    deviceUsed: "Samsung Galaxy A21s",
    category: "medicinal",
    difficulty: "Medium",
    popularity: 65,
    imageUrl: "/placeholder.svg?height=300&width=300&text=White+Willow",
  },
]

// Helper function to get plants by category
export function getPlantsByCategory(category: string): NigerianPlant[] {
  if (category === "all") return nigerianPlantsData
  return nigerianPlantsData.filter((plant) => plant.category === category)
}

// Helper function to search plants
export function searchPlants(query: string): NigerianPlant[] {
  const lowercaseQuery = query.toLowerCase()
  return nigerianPlantsData.filter(
    (plant) =>
      plant.plantName.toLowerCase().includes(lowercaseQuery) ||
      plant.scientificName.toLowerCase().includes(lowercaseQuery) ||
      plant.localNames.toLowerCase().includes(lowercaseQuery) ||
      plant.benefits.toLowerCase().includes(lowercaseQuery) ||
      plant.uses.toLowerCase().includes(lowercaseQuery),
  )
}

// Helper function to get plant categories
export function getPlantCategories(): string[] {
  const categories = [...new Set(nigerianPlantsData.map((plant) => plant.category))]
  return ["all", ...categories.sort()]
}
